# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem "sqlite3"
#
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000

development:
  adapter: postgresql
  encoding: unicode
  database: pennjunior_development
  pool: 5
  username: penn          # PostgreSQL username
  password: Jupercho11    # PostgreSQL password
  host: localhost         # Ensure this is correct`

test:
  <<: *default
  database: pennjunior_test
  username: penn
  password: Jupercho11
  host: localhost

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  # Optionally, you can override the settings to use the DATABASE_URL directly
  # username: <%= ENV['DATABASE_USERNAME'] %>
  # password: <%= ENV['DATABASE_PASSWORD'] %>
  # host: <%= ENV['DATABASE_HOST'] %>
